// lorem text
const text = [
    `Well, obviously, I'm not a big guy. I'm not a Carl Weathers, par example. It's a jetpack, Michael. What could possibly go wrong? It's one banana Michael, what could it cost, ten dollars? Even though so many people in this office are begging for it. Oh Gob, you could charm the black off a telegram boy. Well, I hope you also carry a spare bowl of candy beans. And I am rock steady. No more dizzies.`,
    `And don't make the water too hot. The scabs come right off. Heyyyy uncle father Oscar. You just grab that brownish area by its points and you don't let go no matter what your mother tells you! George Bush doesn't care about black puppets. Look, you are playing adults…with fully formed libidos, not 2 young men playing grab-ass in the shower. It's a jetpack, Michael. What could go wrong? That was Tom Cruise, the actor. Lucille: They said he was some kind of scientist. But anyhoo, can you believe that the only reason the club is going under is because it's in a terrifying neighborhood?`,
    `I am getting rid of this thing. It has caused me nothing but pride and self-respect. Well excuse me for liking the way they frame my junk! So you take your mom to work every day? Bummer. Moms are such a pain in the ass, huh? It's, like, die already! Oh, I don't have any drugs for sale, unless… did you want me to follow you to your car? Even though so many people in this office are begging for it.`,
    `She's trying to prove that she's closer to my children than I am, but the joke's on her, because she doesn't know how little I care for GOB. You don't want a hungry dove down your pants. She wanted to look 48. I nearly airbrushed her into oblivion. Ended up checking "albino" on the form. Yes, he's like the steel man from The Wizard From Oz. I need a tea to give my dingle less tingle. I've used one adjective to describe myself. What is it? You want your belt to buckle, not your chair. Buster's in what we like to call a light to no coma. In layman's terms, it might be considered a very heavy nap.`,
    `She's a girl, I need to teach her how to be a woman. Within her lies a queen. Let me out that queen. I didn't mean who… I meant… her? I've always been deeply passionate about nature. Perhaps you remember Neuterfest? Buster's in what we like to call a light to no coma. In layman's terms, it might be considered a very heavy nap.`,
    `Are all the guys in here… you know? George Sr: No not all of them. Barry: Yeah. It's never the ones you hope. Tobias Fünke costume.`,
    `Heyyyy Uncle Father Oscar. It was for me. I was going to smoke the marijuana like a cigarette. If you're suggesting I play favorites, you're wrong. I love all of my children equally. I don't care for Gob. One of the guys told me to take my head out of my BOTTOM and get back to work…my BOTTOM! I spent so much time making sweet love on my wife that it's hard to hear anything over the clatter of her breasts. Second-of-ly, I know you're the big marriage expert. Oh I'm sorry, I forgot, your wife is dead. God knows they're squinters.`,
    `Prow scuttle parrel provost Sail ho shrouds spirits boom mizzenmast yardarm. Pinnace holystone mizzenmast quarter crow's nest nipperkin grog yardarm hempen halter furl. Swab barque interloper chantey doubloon starboard grog black jack gangway rutters.`,
    `Deadlights jack lad schooner scallywag dance the hempen jig carouser broadside cable strike colors. Bring a spring upon her cable holystone blow the man down spanker Shiver me timbers to go on account lookout wherry doubloon chase. Belay yo-ho-ho keelhaul squiffy black spot yardarm spyglass sheet transom heave to.`,
  ];

  export {text};